- action:
  - data:
      entity_id: light.upstairs_bathroom_level
    service: light.turn_on
  - data:
      entity_id: switch.upstairs_bathroom_fan_switch
    service: switch.turn_on
  alias: Turn on bathroom light when there is movement
  condition: []
  id: '1513895339095'
  trigger:
  - entity_id: sensor.bathroom_4_in_1_alarm_level
    from: '0'
    platform: state
    to: '255'
- action:
  - data:
      entity_id: light.upstairs_bathroom_level
    service: light.turn_off
  - data:
      entity_id: switch.upstairs_bathroom_fan_switch
    service: switch.turn_off
  alias: Turn off bathroom light when there is no movement
  condition: []
  id: '1513895339378'
  trigger:
  - entity_id: sensor.bathroom_4_in_1_alarm_level
    for:
      minutes: 10
    platform: state
    to: '0'
- action:
  - data:
      entity_id: switch.upstairs_bathroom_fan_switch
    service: switch.turn_on
  alias: Turn on bathroom fan if there is high humidity
  condition: []
  id: '1514470885586'
  trigger:
  - above: '10'
    entity_id: sensor.bathroom_4_in_1_relative_humidity
    platform: numeric_state
    value_template: '{{ states.sensor.bathroom_4_in_1_relative_humidity.state | round(2)
      - states.sensor.hallway_thermostat_humidity.state | round(2)  }}'
- action:
  - data:
      entity_id: switch.upstairs_bathroom_fan_switch
    service: switch.turn_off
  alias: Turn off bathroom fan if low humidity
  condition: []
  id: '1514470950921'
  trigger:
  - below: '10'
    entity_id: sensor.bathroom_4_in_1_relative_humidity
    platform: numeric_state
    value_template: '{{ states.sensor.bathroom_4_in_1_relative_humidity.state | round(2)
      - states.sensor.hallway_thermostat_humidity.state | round(2)  }}'
- action:
  - data:
      entity_id: switch.porch_switch
    service: switch.turn_on
  alias: Turn on Porchlight at Sunset
  condition: []
  id: '1515440853909'
  trigger:
  - event: sunset
    offset: -00:15:00
    platform: sun
- action:
  - data:
      entity_id: switch.porch_switch
    service: switch.turn_off
  alias: Turn off Porchlight at Sunrise
  condition: []
  id: '1515441002360'
  trigger:
  - event: sunrise
    offset: +00:15:00
    platform: sun
- action:
  - data:
      brightness_pct: '100'
      entity_id: light.entry_level
    service: light.turn_on
  alias: Turn on Stairway light when Front Door is opened
  condition: []
  id: '1515770332574'
  trigger:
  - entity_id: sensor.front_door_access_control
    from: '23'
    platform: state
    to: '22'
- action:
  - data:
      home_mode: away
    service: nest.set_mode
  alias: Set Nest to eco mode when no one is home
  condition: []
  id: '1516929503237'
  trigger:
  - entity_id: device_tracker.8fdcf6ee
    from: home
    platform: state
    to: not_home
- action:
  - data:
      home_mode: home
    service: nest.set_mode
  alias: Set Nest to on when someone is home
  condition: []
  id: '1516929582840'
  trigger:
  - entity_id: device_tracker.8fdcf6ee
    from: not_home
    platform: state
    to: home
- action:
  - data:
      message: The mailbox has been opened.
      target:
      - device/Jordan
    service: notify.pushbullet_main
  alias: Notify Jordan on Mailbox Open
  condition: []
  id: '1517356729602'
  trigger:
  - entity_id: sensor.mailbox_access_control
    from: '23'
    platform: state
    to: '22'
- action:
  - data:
      message: Someone has taken the mailbox sensor!
      target:
      - device/Jordan
    service: notify.pushbullet_main
  alias: The mailbox sensor is gone!
  condition: []
  id: '1517525565966'
  trigger:
  - entity_id: sensor.mailbox_burglar
    from: '0'
    platform: state
    to: '3'
- action:
  - data:
      entity_id: light.upstairs_bathroom_level
    service: light.turn_on
  - data:
      entity_id: switch.upstairs_bathroom_fan_switch
    service: switch.turn_on
  alias: Turn on bathroom lights when door opens
  condition: []
  id: '1521592326331'
  trigger:
  - entity_id: sensor.upstairs_bathroom_door_access_control
    from: '23'
    platform: state
    to: '22'
- action:
  - data:
      entity_id: light.upstairs_bathroom_level
    service: light.turn_on
  - data:
      entity_id: switch.upstairs_bathroom_fan_switch
    service: switch.turn_on
  alias: Turn on bathroom lights when door closes
  condition: []
  trigger:
  - entity_id: sensor.upstairs_bathroom_door_access_control
    from: '22'
    platform: state
    to: '23'
- action:
  - data:
      entity_id: light.upstairs_bathroom_level
    service: light.turn_off
  - data:
      entity_id: switch.upstairs_bathroom_fan_switch
    service: switch.turn_off
  alias: Turn off bathroom light when there is no movement in 10 seconds after door close
  condition:
    - condition: state
      entity_id: sensor.bathroom_4_in_1_alarm_level
      state: '0'
      for:
        seconds: 10
  trigger:
  - entity_id: sensor.upstairs_bathroom_door_access_control
    for:
      seconds: 10
    platform: state
    to: '23'
- action:
  - data:
      entity_id: light.upstairs_bathroom_level
    service: light.turn_off
  - data:
      entity_id: switch.upstairs_bathroom_fan_switch
    service: switch.turn_off
  alias: Turn off bathroom light when there is no movement in 10 seconds after door open
  condition:
    - condition: state
      entity_id: sensor.bathroom_4_in_1_alarm_level
      state: '0'
      for:
        seconds: 10
  trigger:
  - entity_id: sensor.upstairs_bathroom_door_access_control
    for:
      seconds: 10
    platform: state
    to: '22'