homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 33.906858
  longitude: -84.301314
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 435
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
# frontend:

frontend:
  # extra_html_url:
  #   - /www/custom_ui/state-card-custom-ui.html
  # extra_html_url_es5:
  #   - /www/custom_ui/state-card-custom-ui-es5.html

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  base_url: https://the-ping-in-the-north.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor:
  - platform: moon
  - platform: cpuspeed
  - platform: speedtest
    minute:
      - 0
      - 15
      - 30
      - 45
    monitored_conditions:
      - download
  - platform: fitbit
    clock_format: 12H
    monitored_resources:
      - "activities/steps"
      - "activities/floors"
  - platform: darksky
    api_key: !secret darksky_apikey
    monitored_conditions:
      - summary
      - temperature
      - apparent_temperature
      - precip_type
      - precip_intensity
      - precip_probability
      - nearest_storm_distance
      - wind_speed
      - hourly_summary
      - temperature_max
      - temperature_min
  - platform: template
    sensors:
      jordan_phone_battery:
        friendly_name: Battery
        unit_of_measurement: '%'
        value_template: "{{ states.device_tracker['8fdcf6ee'].attributes.battery }}"
        icon_template: "
            {% set battery_level = states.device_tracker['8fdcf6ee'].attributes.battery|default(0)|int %}
            {% set battery_round = (battery_level / 10) |int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}"

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.86
    token: !secret xiaomi_vacuum_token

media_player:
  - platform: cast
  # - platform: samsungtv
  #   host: 192.168.1.83
  #   mac: 68:27:37:45:7c:8e
  #   port: 8001

# Text to speech
tts:
  - platform: google
  
device_tracker:
  - platform: nmap_tracker
    hosts: 
    - 192.168.1.66
    - 192.168.1.75
    interval_seconds: 10
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False
  - platform: gpslogger
  
map:

# sensor:
#   platform: pi_hole
#   host: 192.168.0.106
#   monitored_conditions:
#     - ads_blocked_today

google_assistant:
  project_id: homeassistant-33aea
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token

zwave:
  usb_path: /dev/ttyACM0
  
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

notify:
  - name: Mail_Delivery
    platform: pushbullet
    api_key: !secret pushbullet_api_key
