homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 33.906858
  longitude: -84.301314
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 435
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Sets up duckDNS
http:
  api_password: !secret http_password
  base_url: https://the-ping-in-the-north.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Shows the map
map:

# Track the sun
sun:

sensor: !include_dir_merge_list sensor
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.86
    token: !secret xiaomi_vacuum_token

media_player:
  - platform: cast

# Text to speech
tts:
  - platform: google
  
device_tracker:
  - platform: nmap_tracker
    hosts: 
    - 192.168.1.66
    - 192.168.1.75
    interval_seconds: 10
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False
  - platform: gpslogger

google_assistant:
  project_id: homeassistant-33aea
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token

zwave:
  usb_path: /dev/ttyACM0
  
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

notify:
  - name: Mail_Delivery
    platform: pushbullet
    api_key: !secret pushbullet_api_key
