# Displays Jordan's phone's battery percentage
- platform: template
  sensors:
    jordan_phone_battery:
      friendly_name: Battery
      unit_of_measurement: '%'
      value_template: "{{ states.device_tracker['8fdcf6ee'].attributes.battery }}"
      icon_template: "
          {% set battery_level = states.device_tracker['8fdcf6ee'].attributes.battery|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}"
          
# Displays Jordan's phone's zone
- platform: template
  sensors:
    jordan_phone_zone:
      friendly_name: Where am I?
      value_template: "{{ states('device_tracker.8fdcf6ee') }}"
      icon_template: "
          {% set loc = states('device_tracker.8fdcf6ee') %}
          {% if loc == 'Beach House' %}
            mdi:beach
          {% elif loc == 'Home'%}
            mdi:home
          {% elif loc == 'not_home'%}
            mdi:road-variant
          {% elif loc == 'Casey''s Parent''s'%}
            mdi:account-multiple
          {% elif loc == 'Casey''s Apartment'%}
            mdi:home-heart
          {% elif loc == 'Jordan''s Parent''s'%}
            mdi:account-multiple
          {% elif loc == 'Work - Slalom'%}
            mdi:briefcase
          {% endif %}"