# Displays Jordan's phone's battery percentage
- platform: template
  sensors:
    jordan_phone_battery:
      friendly_name: Battery
      unit_of_measurement: '%'
      value_template: "{{ states.device_tracker['8fdcf6ee'].attributes.battery }}"
      icon_template: "
          {% set battery_level = states.device_tracker['8fdcf6ee'].attributes.battery|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}"